# Generated by Django 4.2.30 on 2026-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_name_remove_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scope',
            field=models.CharField(default='organization', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
