# Generated by Django 4.2.30 on 2026-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_revertible',
            field=models.BooleanField(default=False),
        ),
    ]
