# Generated by Django 4.2.30 on 2026-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingwork',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='billingwork',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingwork',
            name='work_type',
            field=models.CharField(default='Deliverable Production', max_length=100),
        ),
    ]
