# Generated by Django 4.2.30 on 2026-09-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_account_holder_employee_account_number_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='period',
            field=models.CharField(default='2026-09', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='name',
            field=models.CharField(default='Salary Slip', max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted to CEO', 'Submitted to CEO'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='Draft', max_length=50),
        ),
    ]
