# Generated by Django 4.2.30 on 2026-09-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salaryslip_base_salary_salaryslip_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Locked by HR', 'Locked by HR'), ('Approved by CEO', 'Approved by CEO'), ('Rejected by CEO', 'Rejected by CEO'), ('Disbursed', 'Disbursed')], default='Draft', max_length=50),
        ),
    ]
