# Generated by Django 4.2.30 on 2026-08-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_id', models.CharField(help_text='Synthetic work ID e.g. WORK-101', max_length=50)),
                ('work_type', models.CharField(default='Claim Processing', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(default='New', max_length=50)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('target_quantity', models.IntegerField(default=1)),
                ('actual_quantity', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_effort_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('actual_effort_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('progress', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('assigned_employee', models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_emp', to=settings.AUTH_USER_MODEL)),
                ('assigned_tl', models.ForeignKey(blank=True, limit_choices_to={'role': 'tl'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_tl', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_work', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_work', to='processes.process')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'work_id')},
            },
        ),
    ]
