# Generated by Django 4.2.30 on 2026-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finance_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tl', 'Manager / Team Lead'), ('hr', 'HR'), ('employee', 'Employee'), ('ceo', 'CEO'), ('operations_head', 'Operations Head')], default='employee', max_length=20),
        ),
    ]
