# Generated by Django 4.2.30 on 2026-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_finance_access_user_is_owner_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tl', 'Team Lead'), ('hr', 'HR'), ('employee', 'Employee'), ('ceo', 'CEO'), ('operations_head', 'Operations Head')], default='employee', max_length=20),
        ),
    ]
