# Generated by Django 4.2.30 on 2026-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='college_university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='declaration_candidate_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='declaration_signature',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='district_suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_10th_marksheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_12th_diploma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_approved_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_degree_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_pan_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_passport_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_semester_marksheets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(default='full_time', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='percentage_cgpa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state_postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
