# Generated by Django 4.2.30 on 2026-08-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(help_text='Unique client code', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('onboarding', 'Onboarding')], default='onboarding', max_length=20)),
                ('sla', models.JSONField(blank=True, default=dict, help_text="SLA criteria e.g. {'tat_hours': 24, 'accuracy_target': 98.5}")),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text="Working hours config e.g. {'start': '08:00', 'end': '17:00'}")),
                ('escalation_rules', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('ops_head', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['operations_head', 'ceo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients_ops', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('tl', models.ForeignKey(blank=True, limit_choices_to={'role': 'tl'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients_tl', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'client_id')},
            },
        ),
    ]
