# Generated by Django 4.2.30 on 2026-09-24 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ops_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['operations_head', 'ceo', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients_ops', to=settings.AUTH_USER_MODEL),
        ),
    ]
