# Generated by Django 4.2.30 on 2026-08-26 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('industry', models.CharField(default='Healthcare', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('holiday_policy', models.TextField(blank=True, null=True)),
                ('attendance_rules', models.JSONField(blank=True, default=dict)),
                ('leave_rules', models.JSONField(blank=True, default=dict)),
                ('incentive_rules', models.JSONField(blank=True, default=dict)),
                ('overtime_rules', models.JSONField(blank=True, default=dict)),
                ('notification_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
