# Generated by Django 4.2.30 on 2026-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='designations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='task_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='workflows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(default='Professional Services', max_length=100),
        ),
    ]
